"""Added jobservice table , addded missing fields in job table and did some cleanups

Revision ID: aa46345d7c05
Revises: e874e028ea1a
Create Date: 2026-09-21 21:45:56.410733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa46345d7c05'
down_revision: Union[str, Sequence[str], None] = 'e874e028ea1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobservices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('job_status', sa.String(), nullable=False))
    op.add_column('jobs', sa.Column('total_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'total_price')
    op.drop_column('jobs', 'job_status')
    op.drop_table('jobservices')
    # ### end Alembic commands ###
