"""Added Job Table

Revision ID: e874e028ea1a
Revises: 1034529d4762
Create Date: 2026-09-21 20:57:20.846468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e874e028ea1a'
down_revision: Union[str, Sequence[str], None] = '1034529d4762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('pricing_type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('gst_percentage', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('work', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('business', 'gst_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('business', 'website',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('business', 'address_line2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('client', 'address_line2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'address_line2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('business', 'address_line2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('business', 'website',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('business', 'gst_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('jobs')
    op.drop_table('services')
    # ### end Alembic commands ###
